version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=945313
      - DB_NAME=billing-system
    restart: always

  db:
    image: postgres:14.18-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 945313
      POSTGRES_DB: billing-system
    ports:
      - "5431:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
